twig:
    default_path: '%kernel.project_dir%/templates'
    date:
        timezone: 'Europe/Paris'
    paths: 
        '%kernel.project_dir%/assets/images': images
    form_themes: ['bootstrap_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true
